name: Auto generate formatted commit message

on:
    push:
        branches-ignore: [master develop release]

jobs:
    opencommit:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Setup Node.js Environment
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Generate commit message by OpenCommit
              uses: di-sukharev/opencommit@github-action-v1.0.4
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              env:
                  OCO_AI_PROVIDER: deepseek
                  OCO_API_KEY: ${{ secrets.OCO_API_KEY }}
                  OCO_API_URL: "https://api.deepseek.com/v1"
                  OCO_TOKENS_MAX_INPUT: 8192
                  OCO_TOKENS_MAX_OUTPUT: 2048
                  OCO_DESCRIPTION: true
                  OCO_EMOJI: true
                  OCO_MODEL: deepseek-chat
                  OCO_LANGUAGE: en
                  OCO_PROMPT_MODULE: conventional-commit
